### ISSUE TITLE
[ARTICLE-IDEA] Asthetic Scrollbars

### ISSUE THREAD

**Issue by fescherer** [fescherer/blog#45]
Create asthetic scrollbars. That works on almost all browsers. And more, as this is just a class, you can leave the main scrollbar that right way, the default, and just stylelize your projects scrollbars

Ref. Got these properties from reddit pages aside blocks;
Ref. 2 [Kevin Powell dealing with devices with no hover](https://www.youtube.com/watch?v=uuluAyw9AI0)
Ref. 3 Scrollbar css browser compatibility [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) [:webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar)
![Image](https://github.com/fescherer/blog/assets/62115215/9489416f-9ace-4efb-81b0-c2aee0503ff5)
![Image](https://github.com/fescherer/blog/assets/62115215/2859d25e-e2e8-45e4-90da-777dd5417bb0)

```css
/* Webkit for chrome and normal styles for firefox */

:root {
  --styled-scrollbar-background: white; /* Necessary to be color, does not work if `transparent` */
  --scrollbar-background: green; /*  */
  --color-neutral-border: black; /* Actual color of the scrollbar */
}

/* Firefox Only */
/* Aproches mobile first, because here, the ``scrollbar-color` will be set and always will be that color, but on desktop, that we have hover effect, we can give a transparent color, but how this is mobile first, we give the color here, and treat the desktop in other style */
.styled-scrollbars { 
  scrollbar-color: var(--color-neutral-border) var(--color-neutral-border);
  scrollbar-width: thin; 
}

/* Chrome and others Browsers  */
.styled-scrollbars::-webkit-scrollbar {
  width: 16px;
  height: 16px
}

/* Chrome and others Browsers  */
.styled-scrollbars::-webkit-scrollbar-track {
  background: var(--styled-scrollbar-background)
}

/* With device has hover (Destop or TV, etc) give a little effect on hover  */
@media (hover: hover) {
  .styled-scrollbars {
    scrollbar-color: transparent transparent;
  }

  .styled-scrollbars:hover {
    scrollbar-color: var(--color-neutral-border) transparent
  }

  .styled-scrollbars:hover::-webkit-scrollbar-thumb {
    background: var(--color-neutral-border);
    border: 6px solid var(--styled-scrollbar-background);
    border-radius: 8px;
    -ms-overflow-style: none;
    scrollbar-width: none;
  }
}
```
